# Generated by Django 6.0.3 on 2026-06-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flouristapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='kids',
            options={'verbose_name_plural': 'Kids'},
        ),
        migrations.AlterModelOptions(
            name='men',
            options={'verbose_name_plural': 'Men'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name_plural': 'Women'},
        ),
    ]
