# Generated by Django 6.0.3 on 2026-06-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flouristapp', '0002_alter_home_options_alter_kids_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kids',
            options={},
        ),
        migrations.AlterModelOptions(
            name='men',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={},
        ),
    ]
