# Generated by Django 6.0.3 on 2026-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flouristapp', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=200),
        ),
    ]
