# Generated by Django 6.0.3 on 2026-06-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flouristapp', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist/'),
        ),
    ]
