# Generated by Django 6.0.3 on 2026-06-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flouristapp', '0009_alter_order_price_alter_wishlist_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
